spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:///C:/movieclub/uploads/
app:
  storage:
    location: C:\Users\Krystian\Documents\Movieclub\uploads