spring:
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin
  liquibase:
    contexts: dev
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
app:
  storage:
    location: ./uploads/